from enum import Enum


class AnchorStatus(str, Enum):
    LOCAL_COMMITTED = "LOCAL_COMMITTED"
    PENDING_TRANSPARENCY = "PENDING_TRANSPARENCY"
    ANCHORING = "ANCHORING"
    TRANSPARENCY_ANCHORED = "TRANSPARENCY_ANCHORED"
    RETRYING = "RETRYING"
    FAILED = "FAILED"
